config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'public#home'

  get '/adminportal' => 'admins#portal'
  get '/admindashboard' => 'admins#index'

  resources :admins

  resource :admin do
    resources :public_texts, only: [:edit, :update, :index]
    resources :episodes do
      resource :episodeimage, only: [:destroy]
    end
  end




  # DELETE '/admin/episodes/:id/episode_image'

  post '/session' => 'sessions#create'
  delete '/session' => 'sessions#delete'
end

app/models/public_text.rb
class PublicText < ApplicationRecord
end

app/controllers/public_texts_controller.rb
class PublicTextsController < ApplicationController
  before_action :set_current_admin
  before_action :boot_anonymous, only: [:edit, :index]
  before_action :set_public_text, only: [:edit, :update]
  before_action :set_section_to_public_texts


  def index
    @public_texts = PublicText.all
  end

  def edit
  end

  def update
    return head(401) unless @current_admin
    @public_text.update_attribute(:body, public_text_params[:body])
    redirect_to admin_public_texts_path
  end


  private

  def set_public_text
    @public_text = PublicText.find(params[:id])
  end

  def public_text_params
    params.require(:public_text).permit(:body)
  end

  def set_section_to_public_texts
    @section = "public_texts"
  end

  def set_current_admin
    @current_admin = current_admin
  end

end

app/helpers/public_texts_helper.rb
module PublicTextsHelper
end

app/views/public_texts/_form.html.erb
  <%= form_with(model: public_text, class: "public_text_form", url: admin_public_text_path(@public_text), local: true) do |form| %>
    <% if public_text.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(public_text.errors.count, "error") %> prohibited this public_text from being saved:</h2>

        <ul>
        <% public_text.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      <h1><%= @public_text.public_text_name %></h1>
      <%= form.label :body, "Body" %>
      <%= @public_text.public_text_name.include?("date") ? form.date_field(:body) : form.text_area(:body)%>

    <div class="actions">
      <%= form.submit "Update"%>
    </div>
  <% end %>

app/views/public_texts/edit.html.erb
<%= render "admins/admin_nav" %>
<div class="page_content">
  <%= render 'form', public_text: @public_text %>
  <br>
</div>

app/views/public_texts/index.html.erb
<%= render "admins/admin_nav" %>
<div class="page_content">
  <% @public_texts.each do |public_text| %>
  <div class="public_text">
    <div class="public_text_contents">
      <div class="public_text_name">
        <%= link_to public_text.public_text_name, edit_admin_public_text_path(public_text) %>
      </div>
      <div class="public_text_body">
        <%= public_text.body %>
      </div>
    </div>
    <div class="public_text_edit_button">
      <%= link_to "Edit", edit_admin_public_text_path(public_text) %>
    </div>
  </div>
  <% end %>
</div>