config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'public#home'

  get '/adminportal' => 'admins#portal'
  get '/admindashboard' => 'admins#index'

  resources :admins

  resource :admin do
    resources :public_texts, only: [:edit, :update, :index]
    resources :episodes do
      resource :episodeimage, only: [:destroy]
    end
  end




  # DELETE '/admin/episodes/:id/episode_image'

  post '/session' => 'sessions#create'
  delete '/session' => 'sessions#delete'
end

app/views/admins/_admin_nav.html.erb
<nav class="admin_nav">
  <div class="logo">
    <%=image_tag "admin_logo.png" %>
  </div>
  <div class="admin_links">
    <%= link_to 'episodes', admin_episodes_path, class: @section == "episodes" ? "selected_link" : "" %>
    <%= link_to 'pages', admin_public_texts_path, class: @section == "public_texts" ? "selected_link" : "" %>
    <%= link_to 'admins', admins_path, class: @section == "admins" ? "selected_link" : "" %>
  </div>
  <div class="current_admin">
    <i>Logged in: </i><b><%= @current_admin["email"] %></b><br>
    <%= link_to 'Log out', session_path, :method => :delete %>
  </div>
</nav>
<div class="nav-buffer"></div>

app/views/admins/home.html.erb
Logged in: <%= @current_admin.email %>
<%= link_to('Logout', destroy_admin_session_path, method: :delete) %>

app/views/admins/index.html.erb
<%= render "admins/admin_nav" %>
<div class="notice"><%= notice %></div>
<div class="page_content">
  <div><%= link_to 'new', new_admin_path, class: "new_admin_link" %></div>
  <br>
  <% @admins.each do |admin| %>
    <div class="admin">
      <div class="email_holder">
        <%= admin.email %>
      </div>

        <div class="delete_holder">
          <% unless admin.id == @current_admin['id'] %>
          <%= link_to 'Delete', admin, method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete_admin' %><br>
          <% end %>
     </div>

    </div>
  <% end %>
</div>

app/views/admins/new.html.erb
<%= render "admins/admin_nav" %>
<div class="page_content">
  <%= form_for @admin, :html => {:class => 'admin_input'} do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email, placeholder: "Email" %><br>
  <%= f.label :password %>
  <%= f.password_field :password, placeholder: "Password" %><br>
  <%= f.submit :Create, value: "Create Admin" %>
  <% end %>
</div>

app/views/admins/portal.html.erb
<div class="portal_panel">
  <%= image_tag("/portal_logo.png") %>
  <div class="login_interface">
    <%= form_tag("/session", method: "post") do %>
      <%= text_field_tag(:email, nil, placeholder: 'email') %>
      <%= password_field_tag(:password, nil, placeholder: 'password') %><br><br>
      <%= submit_tag("Log in") %>
    <% end %>
  </div>
</div>