config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/' => 'public#home'

  get '/adminportal' => 'admins#portal'
  get '/admindashboard' => 'admins#index'

  resources :admins

  resource :admin do
    resources :public_texts, only: [:edit, :update, :index]
    resources :episodes do
      resource :episodeimage, only: [:destroy]
    end
  end




  # DELETE '/admin/episodes/:id/episode_image'

  post '/session' => 'sessions#create'
  delete '/session' => 'sessions#delete'
end

app/models/episode.rb
class Episode < ApplicationRecord
  has_one_attached :episode_image
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_current_admin
  before_action :set_episode, only: [:show, :edit, :update, :destroy]
  before_action :set_section_to_episodes
  before_action :boot_anonymous, only: [:index, :show, :new, :edit]

  def index
    @episodes = Episode.all
  end

  def show
  end

  def new
    @episode = Episode.new
  end

  def edit
  end

  def create

    return 0 unless @current_admin
    @episode = Episode.new(episode_params)

    respond_to do |format|
      if @episode.save
        format.html { redirect_to admin_episodes_path, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    return 0 unless @current_admin
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to admin_episode_path(@episode), notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    return 0 unless @current_admin
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to admin_episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def boot_anonymous
      redirect_to adminportal_path unless @current_admin
    end

    def set_episode
      @episode = Episode.find(params[:id])
    end

    def episode_params
      params.require(:episode).permit(:episode_name, :description, :spotify_link, :soundcloud_link, :itunes_link, :episode_image, :episode_number)
    end

    def set_section_to_episodes
      @section = "episodes"
    end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.erb
  <%= form_with(model: episode, class: "episode_form", url: @episode[:id] ? admin_episode_path(@episode) : admin_episodes_path, local: true) do |form| %>
    <% if episode.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

        <ul>
        <% episode.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form_divider">Episode Information</div>
    <div class="episode_input">
      <%= form.label :episode_name, "Episode Name" %>
      <%= form.text_field :episode_name, class: "text_input", placeholder: "Episode Name", id: "episode_name_input" %>
      <%= form.label :episode_number, "Episode Number" %>
      <%= form.text_field :episode_number, class: "text_input", placeholder: "Episode #", id: "episode_number_input" %>
    </div>

    <div  class="episode_input">
      <%= form.label :description, "Episode Description" %>
      <%= form.text_area :description, class: "text_input", placeholder: "Description"  %>
    </div>
    <div class="form_divider">Episode Image</div>
    <div  class="episode_input">
      <%= form.label :episode_image, "Episode Image" %>
      <%= form.file_field :episode_image %>
      <% if @episode.episode_image.attached? %>
        <%= link_to 'Delete Picture', "/admin/episodes/#{@episode.id}/episodeimage", class: "delete_button", method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
    <div class="form_divider">Links</div>
    <div  class="episode_input">
      <%= form.label :spotify_link, "Spotify Link" %>
      <%= form.text_field :spotify_link, class: "text_input", placeholder: "Spotify"  %>
    </div>
    <div  class="episode_input">
      <%= form.label :soundcloud_link, "Soundcloud Link" %>
      <%= form.text_field :soundcloud_link, class: "text_input", placeholder: "Soundcloud"  %>
    </div>
    <div  class="episode_input">
      <%= form.label :itunes_link, "Itunes Link" %>
      <%= form.text_field :itunes_link, class: "text_input", placeholder: "Itunes"  %>
    </div>


    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/episodes/edit.html.erb
<%= render "admins/admin_nav" %>
<div class="page_content">
  <%= render 'form', episode: @episode %>
  <br>
</div>

app/views/episodes/index.html.erb
<%= render "admins/admin_nav" %>
<div class="notice"><%= notice %></div>
<div class="page_content">
  <div><%= link_to 'new', new_admin_episode_path, class: "new_episode_link" %></div>
  <br>
  <% @episodes.each do |episode| %>
    <div class="index_episode">
      <div class="image_holder">
        <% if episode.episode_image.attached? %>
        <%= image_tag(episode.episode_image) %>
        <% end %>
      </div>
      <div class="information">
        <div class="number">
        Episode <%= episode.episode_number %>:
        </div>
        <div class="name">
        <%= episode.episode_name %>
        </div>
        <div class="description">
          <%= episode.description %>
        </div>
      </div>
      <div class="links">
        <%= image_tag("/icon-spotify.png") unless episode.spotify_link == "" %>
        <%= image_tag("/icon-itunes.png") unless episode.itunes_link == "" %>
        <%= image_tag("/icon-soundcloud.png") unless episode.soundcloud_link == "" %>
      </div>
      <div class="management_panel">
        <div class="edit">
          <%= link_to 'Edit', edit_admin_episode_path(episode) %>
        </div>
        <div class="delete">
          <%= link_to 'Delete', admin_episode_path(episode), class: "delete_button", method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
    </div>
  <% end %>
</div>


<br>

app/views/episodes/new.html.erb
<%= render "admins/admin_nav" %>
<div class="page_content">
  <%= render 'form', episode: @episode %>
  <br>
</div>

app/views/episodes/show.html.erb
<%= render "admins/admin_nav" %>
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_admin_episode_path(@episode) %> |
<%= link_to 'Back', admin_episodes_path %>